# This script was automatically generated by Calkit

import calkit


import os
import pandas as pd
import pyrvatrd
import matplotlib.pyplot as plt

exp_perf = pyrvatrd.load_perf_curve(tow_speed=1.0)
sim_perf = pd.read_csv("results/simulation.csv")
fig, ax = plt.subplots()
ax.grid(True)
exp_perf.plotcp(ax=ax, fig=fig)
ax.scatter(sim_perf.tsr, sim_perf.cp, marker="^", color="g", label="Simulated")
ax.legend()

os.makedirs("figures", exist_ok=True)
fig.savefig("figures/cp.png")
calkit.save_notebook_stage_out(fig, stage_name='plot-cp', out_name='fig')
