stages:
  install-rvat-re-dep:
    cmd: calkit runenv --relaxed pip install -q -e ./rvat-re-dep
    always_changed: true
  run-sim:
    cmd: calkit runenv --relaxed python scripts/run-sim.py
    deps:
      - scripts/run-sim.py
      - environment.yml
    outs:
      - results/simulation.csv:
          cache: false
  plot-cp:
    cmd: >
      calkit runenv -n reuse-rvat-re-dep --relaxed --
      python ".calkit/notebook-stages/plot-cp/script.py"
    deps:
      - .calkit/notebook-stages/plot-cp/script.py
      - results/simulation.csv
    outs:
      - .calkit/notebook-stages/plot-cp/outs/fig.pickle
      - figures/cp.png
