stages:
  check-conda-env:
    cmd: calkit check-conda-env -f environment.yml
    deps:
      - environment.yml
    outs:
      - environment-lock.yml:
          cache: false
          persist: true
    always_changed: true
  install-rvat-re-dep:
    cmd: >
      git submodule init
      && git submodule update
      && calkit runenv pip install -q -e ./rvat-re-dep
    always_changed: true
