stages:
  check-conda-env:
    cmd: calkit check-conda-env -f environment.yml
    deps:
    - environment.yml
    outs:
    - environment-lock.yml:
        cache: false
        persist: true
    always_changed: true
  install-rvat-re-dep:
    cmd: calkit runenv pip install -q -e ./rvat-re-dep
    always_changed: true
  run-sim:
    cmd: calkit runenv python scripts/run-sim.py
    deps:
    - scripts/run-sim.py
    - environment-lock.yml
    outs:
    - results/simulation.csv:
        cache: false
  plot-cp:
    cmd: calkit runenv -n reuse-rvat-re-dep -- python ".calkit/notebook-stages/plot-cp/script.py"
    deps:
    - .calkit/notebook-stages/plot-cp/script.py
    - results/simulation.csv
    outs:
    - .calkit/notebook-stages/plot-cp/outs/fig.pickle
    - figures/cp.png
