name: reuse-rvat-re-dep
channels:
  - conda-forge
dependencies:
  - matplotlib
  - pandas
  - jupyter
  - numpy
  - python
  - pip
  - seaborn
  - h5py
  - scipy
  - pip:
      - pxl==0.0.10
      - progressbar
      - calkit-python==0.8.4
